[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "air[standard]>=0.33.1",
    "google-generativeai>=0.8.3",
    "markdown>=3.7",
]
