[project]
name = "tzconverter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "air>=0.35.0",
    "fastapi[standard]>=0.118.0",
]
