[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "air[sql,standard]>=0.33.1",
    "sqlmodel>=0.0.25",
]
